/**
 * Revocation service identification
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticationUrlResponse { 
    /**
     * URL-encoded
     */
    tcTokenUrl: string;
    sessionId: string;
    /**
     * duration of the authenticated session in seconds
     */
    duration: number;
}

