/**
 * Revocation service identification
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * the response to be sent after an error occurred
 */
export interface ErrorResponse { 
    /**
     * error code identifying the error cause
     */
    code: number;
    /**
     * short error description
     */
    message: string;
}

