/**
 * Revocation service identification
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The session data after login.
 */
export interface LoggedInResponse { 
    sessionId: string;
    /**
     * duration of the authenticated session in seconds
     */
    duration: number;
}

