#
# Copyright Bundesdruckerei 2024. Licensed under EUPL-1.2, see the accompanying license file.
#

services:
  pidi.localhost.bdr.de:
    profiles: ["fullStack"]
    depends_on:
      - pid-issuer-mig
      - pid-issuer-db
    image: gcr.io/distroless/java21-debian12:debug
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pid-issuer-db:5432/pididb
      - PIDI_ISSUANCE_SIGNERPATH=/opt/keys/issuance/issuance-test.p12
      - PIDI_ISSUANCE_SIGNERALIAS=1
      - PIDI_ISSUANCE_SEEDPATH=/opt/keys/issuance/seed-test.p12
      - PIDI_BASEURL=${PIDI_BASEURL:-http://pidi.localhost.bdr.de:8080}
      # Configuration of eid identification, settings fit to the governikus sdk samples
      # - PIDI_IDENTIFICATION_SERVER_CERTIFICATESIGPATHS=/opt/keys/test/panstar-signature.cer
      # - PIDI_IDENTIFICATION_SERVER_CERTIFICATEENCPATH=/opt/keys/test/panstar-encryption.cer
      # - PIDI_IDENTIFICATION_SERVER_URL=https://dev.id.governikus-eid.de/gov_autent/async
      # - PIDI_IDENTIFICATION_XMLSIGKEYSTORE_PATH=/opt/keys/test/Governikus_GmbH_&_Co._KG_Localhost_SAML_Signature_620935.p12
      # - PIDI_IDENTIFICATION_XMLSIGKEYSTORE_ALIAS=saml-signature
      # - PIDI_IDENTIFICATION_XMLSIGKEYSTORE_PASSWORD=620935
      # - PIDI_IDENTIFICATION_XMLENCKEYSTORE_PATH=/opt/keys/test/Governikus_GmbH_&_Co._KG_Localhost_SAML_Encryption_466035.p12
      # - PIDI_IDENTIFICATION_XMLENCKEYSTORE_ALIAS=saml-encryption
      # - PIDI_IDENTIFICATION_XMLENCKEYSTORE_PASSWORD=466035
      # - PIDI_IDENTIFICATION_SERVICEPROVIDERNAME=https://localhost:8443

    entrypoint: ["/busybox/sh"]
    command: ["-c", "/usr/bin/java -jar /opt/app/*.jar"]
    volumes:
        - ./eid:/opt/keys/test
        - ./issuance:/opt/keys/issuance
        - ./target:/opt/app

  pid-issuer-db:
    image: postgres:15.8-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pididb
      - POSTGRES_USER=pidi_issuer_mig
      - POSTGRES_PASSWORD=pidi_issuer_mig
      - APP_USER=pidi_issuer_app
      - APP_USER_PASSWORD=pidi_issuer_app
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../docker-compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d pididb -U pidi_issuer_mig"]
      interval: 1s
      timeout: 1s
      retries: 60

  pid-issuer-mig:
    image: liquibase/liquibase:4.29.2@sha256:99bd6047c53ef0751c7d50c4b2ca2fb7e83ba878de5b43cff0cbc0dd1537b47e
    depends_on:
      - pid-issuer-db
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://pid-issuer-db:5432/pididb?escapeSyntaxCallMode=callIfNoReturn
      - RUN_LOCAL=true
      - LIQUIBASE_COMMAND_USERNAME=pidi_issuer_mig
      - LIQUIBASE_COMMAND_PASSWORD=pidi_issuer_mig
      - LIQUIBASE_COMMAND_CONTEXT_FILTER=pidi
    volumes:
        - ./src/main/resources/db:/liquibase/db
    entrypoint: ["/bin/bash"]
    command: ["-c", "/liquibase/docker-entrypoint.sh liquibase --changeLogFile=db/changelog/db.changelog-master.yaml --logLevel=info update && echo done > /tmp/done.txt && sleep infinity"]
    healthcheck:
      test: ["CMD-SHELL", "cat /tmp/done.txt"]
      interval: 1s
      timeout: 1s
      retries: 60

  aa2:
    image: governikus/ausweisapp2
    ports:
      - "24727:24727"
    environment:
      - AUSWEISAPP2_AUTOMATIC_DEVELOPERMODE=true

volumes:
  postgres:
