#
# Copyright 2024 Bundesdruckerei GmbH
# For the license see the accompanying file LICENSE.MD.
#

openapi: 3.0.3
info:
  title: Internal Api
  x-api-id: 9ce7ec1b-aaf4-4e07-8519-252ae2e1eff1
  x-audience: component-internal
  description: API for the status list service
  #  contact: # TODO
  #    name: BDr
  #    email: @bdr.de
  #    url: http://bundesdruckerei.de
  version: 0.3.0
security:
  - ApiKeyAuth: []
paths:
  /pools/{id}/new-references:
    post:
      description: Returns amount references from a pool
      operationId: newReferences
      responses:
        default:
          description: error occurred - see status code and error object for more information.
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "200":
          description: Retrieved references
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/References'
    parameters:
      - name: id
        in: path
        description: The id of the status list pool
        required: true
        schema:
          type: string
      - name: amount
        in: query
        description: The number of references to retrieve
        schema:
          type: integer
          format: int32
          minimum: 1
          default: 1
      - name: X-Api-Key
        in: header
        schema:
          type: string
  /status-lists/update:
    patch:
      description: Sets a status reference to a given value
      operationId: updateStatus
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        default:
          description: error occurred - see status code and error object for more information.
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "204":
          description: Status successfully set
      parameters:
        - name: X-Api-Key
          in: header
          schema:
            type: string
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Api-Key
      description: The api key for the used status list pool
  schemas:
    Reference:
      type: object
      required:
        - uri
        - index
      properties:
        uri:
          type: string
        index:
          type: integer
          format: int32
          minimum: 0
    References:
      type: object
      properties:
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
    UpdateStatusRequest:
      type: object
      required:
        - uri
        - index
        - value
      properties:
        uri:
          type: string
        index:
          type: integer
          format: int32
          minimum: 0
        value:
          type: integer
          format: int32
          minimum: 0
          maximum: 255
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          x-extensible-enum:
            - UNAUTHORIZED
            - NO_SUCH_POOL
            - NO_SUCH_LIST
            - VALUE_OUT_OF_RANGE
            - INDEX_OUT_OF_BOUNDS
            - RATE_LIMIT_REACHED
            - UNSUPPORTED_MEDIA_TYPE
        message:
          type: string
