= PID-Issuer

== Structure

The PID-Issuer contains two main directories:

* `app` - the java code of the project
* `docker` - the docker stuff of the project

The deployment configuration (helm charts) is stored in a sibling
repository "infrastructure".

=== Prerequisites

The integration tests started by maven need a hostname `pidi.localhost.bdr.de` which points to `localhost`.

There is a dns entry for that, but you need a working dns resolving when running the tests. If you work in a closed environment you have to take care yourself, e.g. by editing the hosts file.

=== Run

We use maven as our build system. To build the code run:
[source,bash]
----
$ ./app/mvnw -f ./app/pom.xml package
----

To run the docker compose with the java application built in the previous step run

[source,bash]
----
$ docker compose -f app/compose.yaml --profile fullStack up
----

[TIP]
.Issues building on macOS
====
On macOS with Docker Desktop, there can be problems running this command. When you receive errors starting with `ERROR: failed to authorize: failed to fetch oauth token: Post…`, try to deactivate BuildKit by adding

```json
"features": {
    "buildkit": false
}
```

to the Docker Daemon configuration or by setting:

```bash
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
```
====

== Running

The PID-Issuer requires a database to work properly.
An eID-Client should be part of a Wallet
and a mocked variant is employed in tests.

If local adjustments to the configuration are needed, place them in
a "local" Spring profile (`application-local.properties`). Don't add this file to git.

The PID-Issuer with its database and eid mock can be started with

[source,bash]
----
$ docker compose --profile fullStack up
----

The database as well as the eid mock can be started and initialized via

[source,bash]
----
$ docker compose up
----

[TIP]
.Issues running on macOS
====
When it gets to an error such as `usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/init-user-db.sh: /bin/bash: bad interpreter: Permission denied`, this is most probably related to wrong file permissions. This can be fixed with

```bash
$ chmod +x docker-compose/db/docker-entrypoint-initdb.d/init-user-db.sh
```

A partially initialized, corrupt database can be removed by using

```bash
$ docker compose down -v
```
====

After this the issuer can be started with the "play" buttons from within the IDE or by

[source,bash]
----
$ ./app/mvnw -f ./app/pom.xml spring-boot:run
----

The PID-Issuer is available on port 8080 after startup.

== Testing

We use different components in testing the PID-Issuer. We want to have:

* unit-tests with junit
* integration-tests using spring-boot-tests
* architecture tests using archunit and spring-boot-modulith
* xray to trace our requirements

=== Testing the core

The core components should be tested by plain junit-tests. Use mockito if needed.

=== Integration testing

Our integration tests are placed in the package `de.bdr.pidi.end2end`. There are tow different types of integration tests:

* MockMVC based tests in the `restdoc` package
* Tests with a real http client based in the `remote` package

The integration tests serve two different goals: they should of course guarantee the correctness of our  implementation, but they also document the rest interface with Spring REST Docs.

==== Test setup

We use RequestBuilders for convenience. There is one builder per request type. They have all the correct parameter per request as "with" methods, e.g.: `AuthorizationRequestBuilder#withClientId(String)` and also generic methods to set parameters as needed.

Use the `withDocumentation(String)` method to create snippets for the documentation.

The URLs and other setting for the tests are set by the property `TEST_CONFIG`, which defaults to `plain`.

|===
|Value |Description |Explanation

|`plain` | Test against a local deployment | manually start `docker compose --profile fullStack up`

|`pidi-dev` |Test against the dev stage | manually start `docker compose up`

|`pidi-test` |Test against the test stage | manually start `docker compose up`

|`pidi-demo` |Test against the demo stage | manually start `docker compose up`

|===

==== Remote tests

For tests against a _deployed_ system extend from the `de.bdr.pidi.end2end.remote.RemoteTest` class.

These tests are tagged with the `remote` tag and are **not** executed by default. You can execute them with:

[source,bash]
----
$ ./app/mvnw -f ./app/pom.xml spring-boot:run
$ ./app/mvnw -f ./app/pom.xml verify -Dtest.groups=remote
----

OR simply hit the play button on IntelliJ for the pidi Application and then run a test using the play button

Tests against a remote instance, for example dev, can be started using the following command:

[source,bash]
----
$ docker compose -f app/compose.yaml -f app/compose.pidi-dev.yaml up
$ ./app/mvnw -f ./app/pom.xml verify -DTEST_CONFIG=pidi-dev -Dtest.groups=remote
----

=== Xray

Xray creates tickets for every test in jira. Please give your test cases nice names. Don't be shy to use the `@DisplayName` annotation.

If your tests is linked to a requirement use the `@Requirement` annotation to link the test to it.

If you want to rename tests which already have a xray ticket linked to them use the `@XrayTest` annotation to keep the link.


=== Spring REST Docs tests
https://docs.spring.io/spring-restdocs/docs/current/reference/htmlsingle/[Spring REST Docs] tests serve the purpose of supporting the documentation of a REST API by sending example requests to a running application instance through unit tests. Those requests and the correlated responses are then recorded and transformed to AsciiDoc snippets. The latter can than get integrated into an AsciiDoc based documentation with both, generated and custom authored parts.

==== Running
Spring REST Docs tests are derived from `RestDocTest` and tagged as `e2e`. These tests are also run with

[source,bash]
----
$ ./app/mvnw -f ./app/pom.xml spring-boot:run
$ ./app/mvnw -f ./app/pom.xml verify -Dtest.groups=restdocEid
----

==== Documentation snippets
After running the tests, the AsciiDoc snippets for requests and responses can be found in `${project.build.directory}/generated-snippets`. In their structure, the snippets follow the different issuance variants, verifiable credential formats and protocol endpoints. The following directory listing gives an example:

[source,bash]
----
├── c
│   ├── mdoc
│   │   ├── authorize
│   │   │   ├── curl-request.adoc
│   │   │   ├── http-request.adoc
│   │   │   ├── http-response.adoc
│   │   │   ├── httpie-request.adoc
│   │   │   ├── request-body.adoc
│   │   │   └── response-body.adoc
│   │   ├── credential
│   │   │   ├ …
│   ├── mdoc-batch
│   │   ├── authorize
│   │   │   ├── curl-request.adoc
│   │   │   ├── http-request.adoc
│   │   │   ├── http-response.adoc
│   │   │   ├── httpie-request.adoc
│   │   │   ├── request-body.adoc
│   │   │   └── response-body.adoc
│   │   ├── credential
│   │   │   ├ …
----

==== Snippet based documentation
The snippets can be included in AsciiDoc based documentation, then. This documentation can be found in link:./app/src/docs/asciidoc/manual.adoc[manual.adoc].

After building the project with

[source,bash]
----
$ ./app/mvnw -f ./app/pom.xml package
----

, an HTML version of the documentation is available in `${project.build.directory}/generated-docs/manual.html`.